feat: added list of borrowable items
HE-Arc/Giraffe-Palladium pull request #26
Opened 2022-11-30 15:32 UTC by seba-chappuis

2022-11-30 16:13 UTC, Xstoudi requested changes

2022-11-30 16:13 UTC, Xstoudi commented on routes/web.php
> +Route::get('/items/borrowable', [ItemController::class, 'index'])->name('items.index');
L'URL est pas trop approprié au nom de la route et à la méthode utilisée dans le contrôleur.
Je vous propose de remplacer l'URL `/items/borrowable` par `/items`.

2022-11-30 16:13 UTC, Xstoudi commented on app/Http/Controllers/ItemController.php
> +        // Get all shares that that are borrowable, they are referenced in the Share table
Y a une incompréhension du schéma ici je pense.

On a des `shares` qui ont un lender mais pas de borrower dans le seeding de la DB ?

Normalement un objet dont l'emprunt est conclut devrait avoir un lender et un borrower et un `share` créé.

2022-11-30 17:29 UTC, Ozurah commented on app/Http/Controllers/ItemController.php
> +        // Get all shares that that are borrowable, they are referenced in the Share table
> On a des shares qui ont un lender mais pas de borrower dans le seeding de la DB ?
Oui.

Enfaite le problème viens de notre conception de la DB, ce qui fait que `shares` et `item` ont une relation 1-1.

En soit comme c'est designé, l'utilisateur quand il créé un objet, une entrée "partage" doit aussi être créer. La table `item` correspond aux informations d'un objet, tandis que `share` à la configuration et au partage de l'objet...
Avoir un objet sans personne l'ayant emprunter permet notamment de  définir une date butoir, et de configurer sa visibilité aux autres utilisateurs.

2022-11-30 17:32 UTC, Ozurah commented on routes/web.php
> +Route::get('/items/borrowable', [ItemController::class, 'index'])->name('items.index');
Pour moi, ça me va de changer par `/items`.

Pourquoi on avait mis `items/borrowable` : 
- Quand on avait définit les routes, on avait dit que l'URI serait plus parlante pour les utilisateurs. De cette manière ils voient `objets > empruntables`.
Mais ça ne respecte pas les conventions Laravel pour les routes de bases, tel qu'`index`.

2022-12-03 12:25 UTC, Ozurah commented on app/Http/Controllers/ItemController.php
> +        // Get all shares that that are borrowable, they are referenced in the Share table
**Après réunion** nouvelle issue: #29, visant à corriger ce problème de compréhension.

Il faudra corrigé après qu'une PR fixant l'issue mentionné soit faite.

2022-12-06 19:44 UTC, Ozurah commented
En se basant que sur le dernier commit 9c67372, ça me semble correct.
> Comme du commit a9849ec au 9af38a3, il s'agit simplement du fait que la branche `main` a été rejoué sur la branche, les changements n'ont pas été jugé

2022-12-06 19:48 UTC, Ozurah commented on app/Http/Controllers/ItemController.php
> +        $items = Item::where('listed', true)
Par contre, je pense qu'il serait intéressant de mettre ce code coté modèle. Comme sa on peut l'utiliser pour la page d'un utilisateur (comme elle contient la liste des objets qu'il propose)

2022-12-06 19:48 UTC, Xstoudi commented on app/Http/Controllers/ItemController.php
> +        $items = Item::where('listed', true)
+1

2022-12-07 07:44 UTC, Ozurah approved these changes

2022-12-07 13:10 UTC, merged