Feat/active shares
HE-Arc/Giraffe-Palladium pull request #27
Opened 2022-11-30 15:43 UTC by Ozurah

Page structure "my borrows" is done

2022-11-30 15:50 UTC, seba-chappuis approved these changes

2022-12-02 14:47 UTC, Xstoudi requested changes

2022-12-03 11:23 UTC, Ozurah commented on app/Models/Share.php
> +        return $this->belongsTo(Item::class, 'item_id');
D'après ce que j'ai lu, le `belongsTo` est dans la classe contenant le champ `aaa_id`.

Donc je pense qu'on est juste.


> https://laravel.com/docs/9.x/eloquent-relationships#one-to-one 
> - a User model might be associated with one Phone model. To define this relationship, we will place a phone method on the User model. The phone method should call the hasOne
> - let's define a relationship on the Phone model that will let us access the user that owns the phone. We can define the inverse of a hasOne relationship using the belongsTo
>
> autre exemple : https://www.semicolonandsons.com/code_diary/databases/difference-between-has-one-belongs-to-and-has-many

2022-12-03 13:13 UTC, Xstoudi approved these changes

2022-12-03 15:19 UTC, merged