Feat/asks management
HE-Arc/Giraffe-Palladium pull request #41
Opened 2022-12-09 12:04 UTC by seba-chappuis

2022-12-10 10:44 UTC, Ozurah requested changes
Je ne sais pas se qu'il c'est passé dans l'historique des commits, mais visiblement seul le dernier est à prendre en compte. Les précédents sembles être ceux qui ont été validés lors de la PR #26.

2022-12-10 10:44 UTC, Ozurah commented on app/Http/Requests/AcceptAskRequest.php
> +            'deadline.date' => 'Please enter a valid date',
Tous nos messages d'erreurs sont en français (dans les autres classes `Request`).
D'ailleur le `StoreAskRequest` (non modifié dans cette PR) fait exception, il faudrait le corrigé aussi

2022-12-10 10:44 UTC, Ozurah commented on resources/views/components/asks.blade.php
> +    $share (App\Models\Share)
Mauvaises indications des variables

2022-12-11 14:39 UTC, Xstoudi commented
1. Quand il y a plusieurs demandes d'emprunt sur le même objet et qu'on accepte l'une d'entre elles, il faut rejeter les autres.
2. Il faut ajouter un lien vers "Demandes d'emprunt"

2022-12-12 17:41 UTC, Ozurah approved these changes

2022-12-12 17:42 UTC, merged